### ISSUE TITLE
As an organizer I want to create a new event and generate a unique promotional QR code that links to the event description and event poster in the app (medium risk)

### ISSUE THREAD

**Issue by roger-chau** [CMPUT301F24dreams/dreams-Athena#12]

**Comment by Ahmed-S7** [comment]
Upon event creation:
- the user will add all of the necessary fields for the event using edit Texts

When the event is created by clicking create event:
- A QR code for the event will be generated and added to the DB
- An event with all of the respective fields will also be added to the DB
- whenever the event is displayed, if the viewing user is and admin, they will have an option to delete the event and QR code
- if the user is a non-admin, they will be able to view the event details such as name and registration date
